name: Build HuskSync

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/HuskClaims.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: 'Build HuskClaims .jar'
        run: |
          rm -rf HuskClaims
          git clone https://github.com/WiIIiam278/HuskClaims
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd HuskClaims
          ./gradlew clean build

      - uses: actions/upload-artifact@v3
        with:
          name: HuskClaims
          path: HuskClaims/target/*.jar
