name: Build RayTraceAntiXray

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/Build RayTraceAntiXray.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 'Build RayTraceAntiXray .jar'
        run: |
          set -e
          echo "Starting build process"
          rm -rf RayTraceAntiXray || { echo "Failed to remove old directory"; exit 1; }
          git clone https://github.com/stonar96/RayTraceAntiXray || { echo "Git clone failed"; exit 1; }
          git config --global user.email "you@example.com" || { echo "Git config email failed"; exit 1; }
          git config --global user.name "Your Name" || { echo "Git config name failed"; exit 1; }
          cd RayTraceAntiXray || { echo "Failed to change directory"; exit 1; }
          echo "Running Maven build"
          ./compilew.sh || MAVEN_EXIT_CODE=$? # Capture the Maven exit code
          echo "Maven exited with code $MAVEN_EXIT_CODE"
          if [ $MAVEN_EXIT_CODE -eq 1 ]; then
            echo "Maven build completed with known exit code 1, treating as success"
            MAVEN_EXIT_CODE=0
          fi
          if [ $MAVEN_EXIT_CODE -ne 0 ]; then
            echo "Maven build failed with exit code $MAVEN_EXIT_CODE"
            exit $MAVEN_EXIT_CODE
          fi
          echo "Build process completed successfully"

      - name: Verify Build Output
        run: |
          if [ ! -f RayTraceAntiXray/RayTraceAntiXray/target/raytraceantixray-*.jar ]; then
            echo "Build artifact not found"
            exit 1
          else
            echo "Build artifact found"
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: RayTraceAntiXray
          path: RayTraceAntiXray/RayTraceAntiXray/target/raytraceantixray-*.jar
