name: Build Coreprotect

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/Build Coreprotect.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Step 3: Install Maven
    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    # Step 4: Modify the plugin.yml file
    - name: Modify plugin.yml
      run: |
        sed -i 's/${project.branch}/development/' src/main/resources/plugin.yml

    # Step 5: Build the plugin
    - name: Build CoreProtect
      run: |
        mvn clean install

    # Step 6: Save the output
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: coreprotect-jar
        path: target/CoreProtect-*.jar
