name: Build CoreProtect

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/Build_CoreProtect.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone or update CoreProtect repository
        run: |
          if [ -d "CoreProtect" ]; then
            echo "Repository exists. Updating..."
            cd CoreProtect && git pull
          else
            echo "Cloning repository..."
            git clone https://github.com/PlayPro/CoreProtect.git
          fi

      - name: Set up JDK 21 and Maven cache
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Modify plugin.yml file
        working-directory: CoreProtect
        run: sed -i 's/\${project.branch}/development/' src/main/resources/plugin.yml

      - name: Build CoreProtect plugin
        working-directory: CoreProtect
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: coreprotect-jar
          path: CoreProtect/target/CoreProtect-*.jar
