name: Build HuskTowns

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/HuskTowns.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: 'Build HuskTowns .jar'
        run: |
          rm -rf HuskTowns
          git clone https://github.com/WiIIiam278/HuskTowns
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd HuskTowns
          ./gradlew clean build

      - uses: actions/upload-artifact@v3
        with:
          name: HuskTowns
          path: HuskTowns/target/*.jar

