name: Build HuskTowns with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 'Build Folia .jar'
        run: |
          git clone https://github.com/WiIIiam278/HuskTowns
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd HuskTowns
          ./gradlew clean build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ path.basename(path.join('HuskTowns', 'build', 'libs', '*')) }}
          path: HuskTowns/build/libs/*.jar

