name: Build Oraxen

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/Oraxen.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: 'Build Oraxen .jar'
        run: |
          rm -rf oraxen
          git clone https://github.com/oraxen/oraxen
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd oraxen
          chmod +x ./gradlew
          ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: oraxen
          path: oraxen/build/libs/*.jar
